### ISSUE TITLE
If changing initializer row number, it will report error

### ISSUE THREAD

**Issue by miaomiaomiaomiaomiao** [pyexcel/django-excel#10]
In the initializer, if change the row index that has the field names, let's say the default is "0", if changed to "1" or "2" which means in Excel, the field row is not the first row anymore. It will report errors like C:\Python27\lib\site-packages\pyexcel_io\djangobook.py" in __init__for name in self.column_names]
Exception Value: ''

**Comment by chfw** [comment]
How have you changed it? Did you use [name_columns_by_row](https://github.com/chfw/django-excel/blob/master/django_excel/__init__.py#L43) ?

**Comment by chfw** [comment]
Please show me more details.
