### ISSUE TITLE
Test requirements

### ISSUE THREAD

**Issue by girijasameera** [pyexcel/django-excel#11]
I did pip install -r test_requirements.txt

i get an error saying sh1.11 is only supported for linux. download pbs 0.110 for windows.
I downloaded pbs using pip install pbs and ran the above command-
I still get the same error. Does this mean django-excel isn't compatible with windows. How can I finish downloading the rest of the needed dependencies?
Please help.
Thank you

**Comment by chfw** [comment]
test_requirements.txt does not contain sh1.11. And I do most of my development under a windows laptop, so I am sure django-excel is OK in windows environment.

**Comment by girijasameera** [comment]
OK. Thank you.
