### ISSUE TITLE
Package requirement 

### ISSUE THREAD

**Issue by girijasameera** [pyexcel/django-excel#12]
I am working on the tutorial given at http://django-excel.readthedocs.org/en/latest/
I am doing so on Pycharm 5.0.2 on my Windows 7 system.
I get a message when i open the project on Pycharm saying 'Package requirement master.zip not satisfied'
There is an option to install the requirement and even though it says successful installation I still get the same error.
I had done both 
pip install -r requirements.txt
pip install -r test_requirements.txt

How do I make master.zip available. Could I manually download it (if so , please mention a link) and also where(in which folder on my computer) should I save it?

Please help
Thank you.

**Comment by chfw** [comment]
This is related to my latest change. https://github.com/pyexcel/pyexcel-webio/archive/master.zip can be downloaded. And pip will install master.zip.

**Comment by chfw** [comment]
https://www.jetbrains.com/pycharm/help/resolving-unsatisfied-dependencies.html

**Comment by girijasameera** [comment]
Where do I save master.zip after installation ?Which folder?

**Comment by chfw** [comment]
'pip install https://github.com/pyexcel/pyexcel-webio/archive/master.zip' will install from zip.

**Comment by girijasameera** [comment]
Even after successful installation using pip , I still get the message that requirement has not been met.

**Comment by chfw** [comment]
Do you have any issue with this previous commit?  https://github.com/pyexcel/django-excel/commit/3406fb8f6cb21c7d67ccdf004530c6ddd4aa280f

the latest change(pyexcel-webio==0.0.5) will be released once all tests were written, which needs a bit of time.

**Comment by girijasameera** [comment]
OK
http://localhost:8000/polls/export/
is giving me 

Environment:


Request Method: GET
Request URL: http://localhost:8000/polls/export/

Django Version: 1.9.1
Python Version: 2.7.11
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'polls')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')



Traceback:

File "C:\Python27\lib\site-packages\django\core\handlers\base.py" in get_response
  158.                                  % (callback.__module__, view_name))

Exception Type: ValueError at /polls/export/
Exception Value: The view polls.views.export_data didn't return an HttpResponse object. It returned None instead.

**Comment by girijasameera** [comment]
http://localhost:8000/polls/upload gives me page not found that's why i went to http://localhost:8000/polls/export.

**Comment by chfw** [comment]
http://localhost:8000/polls/ should be the right link. I've updated the documentation in the morning.

**Comment by girijasameera** [comment]
Yes that works. It gives me a csv file to download which I don't need. I want to be able to upload data from my excel sheet to my database. So I've been working with http://localhost:8000/polls/ import and
export. Which gave me the above error

**Comment by girijasameera** [comment]
Also when i go to http://localhost:8000/admin/polls/question/ I am unable to delete the questions but I've been able to delete all the choices. Then when I went to http://localhost:8000/polls/ import again I'm getting IOError.

**Comment by girijasameera** [comment]
So as of now there are IOError with import and export.

**Comment by girijasameera** [comment]
I was able to delete all questions and choices. Then when I uploaded sample-data.xls import worked.
But problem is when I upload the same file again. The questions don't repeat but the answers do.i.e. I have duplicates of choices. export doesn't work I still get the IOError as above.

**Comment by chfw** [comment]
Data import was originally intended to transport data from one database to another empty database or another database had partial data. Questions do not repeat is because slug is unique field and django won't duplicate it. Choices repeat otherwise. 

I will try export in a while.

**Comment by girijasameera** [comment]
So the only way to ensure that duplicates of choices don't get saved is to ensure each time a new set of questions and choices are being added. No other way to do this ? Like if by accident the client uploads the same question again?

**Comment by chfw** [comment]
Only these urls are valid, please refer to the documentation:
http://localhost:8000/polls/export/book
http://localhost:8000/polls/export/sheet
http://localhost:8000/polls/export/custom

Meanwhile, I have fixed this IOError in newer code.

**Comment by chfw** [comment]
django-excel import provides the means to do import but does not promise that end user won't do bad things. However, django-excel could have this feature ported over: https://github.com/pyexcel/Flask-Excel/issues/7. 

In other words, the responsibility lies on the developer who uses django-excel and who should make sure such silly thing wont mess up the database.

**Comment by chfw** [comment]
this is the commit https://github.com/pyexcel/django-excel/commit/234a3d7bc634f4b2cc3e296d93651cf9097dc359

**Comment by girijasameera** [comment]
ok.

**Comment by girijasameera** [comment]
Will installing flask-excel ensure that even if database is not empty, new upload will not affect existing entries in database?

**Comment by chfw** [comment]
@girijasameera , please note Flask-Excel is not for Django. This piece of feature needs to be coded up specifically for Django

**Comment by girijasameera** [comment]
Ok. Also I just realized that the previous entries aren't affected by new excel upload . Thanks.
