### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by girijasameera** [pyexcel/django-excel#15]
def import_data(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST,
                              request.FILES)
        def choice_func(row):
            q = Question.objects.filter(slug=row[0])[0]
            row[0] = q
            return row
        if form.is_valid():
            request.FILES['file'].save_book_to_database(
                models=[Question, Choice],
                initializers=[None, choice_func],
                mapdicts=[
                    ['question_text', 'pub_date', 'slug'],
                    ['question', 'choice_text', 'votes']]
            )
            return HttpResponse("OK", status=200)
        else:
            return HttpResponseBadRequest()

In this part of the code , 
How do I modify the code if both sheets were merged in the excel file i.e., If I had one excel sheet with only 7 columns:question_text,published date,choice 1,choice 2 , choice 3,choice 4,right answer
Assuming 1)question model has a field right_answer 2) no slug field in Question 3)no votes filed in Choice model.

Since all choices are in the same row ,I thought i won't need slug field.

Thank You

**Comment by girijasameera** [comment]
I was wondering if after creating the question instance,we could extract the auto-generated id and use  that to create choice instances if there wad just one excel sheet in place of two.

Which custom formatting function are you talking about?

**Comment by chfw** [comment]
Yes, you can do it in that way. However, you shall then be familiar with [data manipulation](http://pyexcel.readthedocs.org/en/latest/tutorial05.html) and [pyexcel.Sheet.save_to_database](http://pythonhosted.org/pyexcel/generated/pyexcel.Sheet.save_to_database.html#pyexcel.Sheet.save_to_database)

**Comment by girijasameera** [comment]
Ok. Thanks will follow that to implement.
