### ISSUE TITLE
Insert tuple value for ModelFields with choices set

### ISSUE THREAD

**Issue by gabn88** [pyexcel/django-excel#19]
I have a modelField, a.k. an IntergerField(choices=((1, 'nice option 1'),(2, 'nice option 2')) 

It now displays a 1 or 2, but it would be really nice if it could show 'nice option 1' or 'nice option 2' instead.

**Comment by chfw** [comment]
I am considering of passing on the extra rendering function per each field while the data is being extracted.

**Comment by chfw** [comment]
Will create another issue to tack this
