### ISSUE TITLE
how could I export sheet with model method as column

### ISSUE THREAD

**Issue by lhsdaniel** [pyexcel/django-excel#22]
So I am trying to use django-excel to export a sheet of a certain model. Problem is there are some methods in this model that I also want to appear in the sheet. I tried to pass in those directly:

```
query_record = Equipment.objects.all().values('manufacturer','_latest_calibration_date',)
return excel.make_response_from_records(
                query_record, 'xls', file_name="sheet")
```
in which manufacturer is a charfield and _latest_calibration_date is a method, and this doesn't work. Trying to save the work of creating the sheet from scratch, I tried this a link that seems to maintain value of a field with a method, and do:

```
_latest_calibration_date = models.DateField(db_column = 'latest_calibration_date')

@property
def latest_calibration_date(self):
    return self._latest_calibration_date

@latest_calibration_date.setter
def latest_calibration_date(self):
    return Calibration.objects.filter(cal_asset__id = self.id).order_by('-id')[0].cal_date
```
Still, this gives me errors like this:

ProgrammingError at /calbase/export/sheet ('42S22', "[42S22] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid column name 'latest_calibration_date'. (207) (SQLExecDirectW)")

**Comment by chfw** [comment]
first of all, it's not supported to pass on method into response yet. 

secondly, records in make_response_from_records expects a list of dictionary that has the same keys. and you are using query, so I think make_response_from_query_sets should be used instead.

however, you would like to put the method in response. I guess you would like to put the result of the method in it. Would you be able to try these?
   
    sheet = get_sheet(query_sets=query_record, column_names=["manufacturer"])
    calibration_dates = ["calibration_date"]
    for obj in Equipment.objects.all():
        calibration_dates.append(obj.latest_calibration_date())
    sheet.column += calibration_dates
    return excel.make_response(sheet, 'xls', file_name='sheet')

I would recommend that you spend some time with the tutorial and the api reference.

**Comment by chfw** [comment]
Will create another issue to address your issue indirectly
