### ISSUE TITLE
custom export with colnames

### ISSUE THREAD

**Issue by weditor** [pyexcel/django-excel#23]
i want to export foreignkey fieds, and i want to change the header,
so i wrote some code like this:
query_sets = Asset.object.all()
column_names = ['name', 'manager__firstname']
sheet_header = ['name', 'manager']
return excel.make_response_from_query_sets(query_sets, column_names, 'xls', file_name="custom", colnames=sheet_header)

but it comes out two headers( column_names and sheet_header) like this:
|name  | manager |
|name  | manager__firstname|
|pen     | aaa |
....more asset list...

i've found no way to salve this problem without modify django-excel.
what should i do?
thanks .

**Comment by chfw** [comment]
you could use 

    sheet = excel.pe.get_sheet(query_sets=query_sets, column_names=column_names)
    sheet.colnames = sheet_header
    excel.make_response(sheet, 'xls',file_name='custom')

**Comment by weditor** [comment]
I'm sorry. but it not work. still comes out with two headers .
sheet.array contains culumn_names and query_sets, it seems that the column_names was treated as data.
now i found it was because pyexcel.sources.database.SheetQuerySetSource.get_data return column_names as first_row with query_sets.

**Comment by chfw** [comment]
Oh, I am sorry. I forgot how it works. It needs a bit of correction:

    sheet = excel.pe.get_sheet(query_sets=query_sets, column_names=column_names)
    sheet.name_columns_by_row(0) # this will take row 0 into colnames
    sheet.colnames = sheet_header
    excel.make_response(sheet, 'xls',file_name='custom')

Otherwise, you could do as well this:


    sheet = excel.pe.get_sheet(query_sets=query_sets, column_names=column_names)
    sheet.row[0] = sheet_header
    excel.make_response(sheet, 'xls',file_name='custom')

**Comment by weditor** [comment]
Good idea. i tried, it salves my problem perfectly. 
thanks.

**Comment by allexiusw** [comment]
Even though you don't achieve the goal with `excel.make_response_from_query_sets()` the solution is really easy to implement. Thanks @chfw ...

**Comment by weditor** [comment]
> Even though you don't achieve the goal with `excel.make_response_from_query_sets()` the solution is really easy to implement. Thanks @chfw ...

such an old question.

yes indeed。cache all lines in list and replace the first line, That was the only way I knew at the time. I asked this question, because I felt it's not pythonic, since the number of rows may be particularly large, but i don't know how and why。i was new to python in 2016。i don't know such things like `iter` / `next` nor `iterools.chain` 。

Hope these informaion are helpful to others like me before.

**Comment by allexiusw** [comment]
You mean that is posible to improve performace if we use `iter()` and `next()` functions? In some way in this particular problem. Thanks for answer in advance, I'm in the path of improve my code and integrate good practices.

**Comment by allexiusw** [comment]
> > Even though you don't achieve the goal with `excel.make_response_from_query_sets()` the solution is really easy to implement. Thanks @chfw ...
> 
> such an old question.
> 
> yes indeed。cache all lines in list and replace the first line, That was the only way I knew at the time. I asked this question, because I felt it's not pythonic, since the number of rows may be particularly large, but i don't know how and why。i was new to python in 2016。i don't know such things like `iter` / `next` nor `iterools.chain` 。
> 
> Hope these informaion are helpful to others like me before.

 You mean that is posible to improve performace if we use `iter()` and `next()` functions? In some way in this particular problem. Thanks for answer in advance, I'm in the path of improve my code and integrate good practices.
