### ISSUE TITLE
Unable to make response from array in Django 1.9

### ISSUE THREAD

**Issue by simkimsia** [pyexcel/django-excel#25]
# Versions
Django 1.9
Django-excel version 0.0.5

# What I did

I tried the make_response_from_array(rows, "xls") where rows is a list of list

# What I expected
To simply work

# What I got
OSError about no file name and no content

**Comment by chfw** [comment]
do you have exception trace back? and can you provide a list of pyexcel packages installed?

**Comment by chfw** [comment]
answer is here: http://stackoverflow.com/questions/40084424/pyexcel-export-error-no-content-file-name-nothing-is-given
