### ISSUE TITLE
import_sheet foreign key

### ISSUE THREAD

**Issue by Bha91** [pyexcel/django-excel#27]
get this error if has foreign key in model "Cannot assign "5": "Choice.question" must be a "Question" instance."

**Comment by chfw** [comment]
yes, you will get it. Please reference [import_data](https://github.com/pyexcel/django-excel/blob/master/polls/views.py#L77)  function where it imports data for two tables.

What you need to do is to write a custom constructor for choice, where you find the question and assign it to Choice.question.

**Comment by Raiuc** [comment]
What if I need to save data to a table using 2 Foreign keys from different tables??
This is my model:

**Comment by chfw** [comment]
The position x is indicated by your [mapping dict](https://github.com/pyexcel/django-excel/blob/master/polls/views.py#L87).

**Comment by Raiuc** [comment]
Thank you chfw.
