### ISSUE TITLE
Exception Value: string indices must be integers, not str

### ISSUE THREAD

**Issue by sindhujit** [pyexcel/django-excel#29]
I am getting the above error when i run django-excel from inside a virtualnev in my work env..
Something is missing or is conflicting in pyexcel:-
/python2.7/site-packages/pyexcel_io-0.3.0-py2.7.egg/pyexcel_io/manager.py in pre_register, line 27

when i hit enter the 2nd time and again after that, i get:-
'module' object has no attribute '_compact'
python2.7/site-packages/pyexcel-0.4.2-py2.7.egg/pyexcel/sheets/sheet.py in <module>, line 12

any quick help is appreciated?

**Comment by chfw** [comment]
Please do pip freeze and upgrade any pyexcel plugins that is lower than 0.3.0.

**Comment by chfw** [comment]
here is the plugin compatibility table: http://pyexcel.readthedocs.io/en/latest/#id4
http://pyexcel-io.readthedocs.io/en/latest/#id5
