### ISSUE TITLE
'tuple' object has no attribute '_meta'

### ISSUE THREAD

**Issue by maxmoriss** [pyexcel/django-excel#30]
Return this error till .xls uploading, here is a code...

```
def form_valid(self, form):
        self.request.FILES['file'].save_book_to_database(
            models=[
                (Question, ['title', 'answer_1', 'answer_2', 'answer_3', 'answer_4', 'correct'], None, 0)
            ]
        )
        return super(QuestionList, self).form_valid(form)
```

Anybody, help!

**Comment by chfw** [comment]
it looks like you have been using older syntax of pyexcel. please look at this example: https://github.com/pyexcel/django-excel/blob/master/polls/views.py#L82

**Comment by dkessel** [comment]
I got this too, using the example from: http://django-excel.readthedocs.io/en/latest/ . Looks like that is outdated.

**Comment by chfw** [comment]
I am sorry that I wasn't aware the example code in rst file was outdated. I will fix it using liternalinclude in rst file so they will stay in sync.
