### ISSUE TITLE
Hyperlinking

### ISSUE THREAD

**Issue by Tomvictor** [pyexcel/django-excel#31]
Hello Sir,
I have deployed django-excel in production. Its working perfectly, thanks.
Is there any method for giving hyperlinks?

Thank you

**Comment by chfw** [comment]
Wow, glad to hear that. What do you by "hyperlinks"?

**Comment by Tomvictor** [comment]
I had deployed a web app, I am using django-excel for the final output.
It will be good, if I can give hyperlink to the uploaded content.
I just tried [this method](https://support.office.com/en-US/article/HYPERLINK-function-333C7CE6-C5AE-4164-9C47-7DE9B76F577F), I works fine on google sheet, but not working in the numbers
Note:
Output format : csv

**Comment by chfw** [comment]
If I understood you correctly, you would like to provide a hyperlink to be able to download the uploaded content. But where would you insert the hyperlink?

**Comment by Tomvictor** [comment]
I have solved the problem using enterting the link in the following format.

_**=HYPERLINK("http://example.microsoft.com/report/budget report.xlsx", "Click for report")**_

**Comment by chfw** [comment]
so you have put it as a value to your cell and the file is to be opened by MS Excel. Hence your end user could click it through. Is my understanding correct? I am trying to understand your use case.

**Comment by Tomvictor** [comment]
@chfw  Yes you are right.
Thanks :)
