### ISSUE TITLE
Blank xls file output

### ISSUE THREAD

**Issue by maltebeckmann** [pyexcel/django-excel#32]
My outputted xls files are all empty/blank, i.e. 0 kB. No indicator as to why this might be happening. I followed the sample code:

def export_data(request, atype):
    if atype == "sheet":
        return excel.make_response_from_a_table(City, 'xls', file_name="cities")

Lots of cities in the db. Running Django 1.9.4, django-excel 0.0.6 and pyexcel 0.4.3. How can I debut this issue?

**Comment by chfw** [comment]
What is your versions of pyexcel-webio, pyexce-io and pyexcel-xls? 

What about a break point at the following location? You can try print(sheet) to see if it has any content.

https://github.com/pyexcel/django-excel/blob/master/django_excel/__init__.py#L154

**Comment by maltebeckmann** [comment]
Thanks for getting back so soon!

pyexcel==0.4.3
pyexcel-io==0.3.2
pyexcel-webio==0.0.10
pyexcel-xls==0.3.1
pyexcel-xlsx==0.3.0

I set a breakpoint just before the line you specified and got this for args:
(Pdb) args
model = <class 'apps.cities.models.City'>
file_type = 'xlsx'
status = 200
file_name = 'sheet'
keywords = {}

When I do runserver and put a print(sheet) just below line 154, like this:
    sheet = pe.get_sheet(model=model, **keywords)
    print(sheet)

I get an error saying 
file_type	'xlsx'
keywords {}
status	200
sheet	Error in formatting: KeyError: <class 'decimal.Decimal'>
file_name 'sheet'
model	<class 'apps.cities.models.City'>

**Comment by maltebeckmann** [comment]
I set a break point just after line 154 and tried print(sheet) and got:
-> return make_response(sheet, file_type, status,
(Pdb) print(sheet)
*** KeyError: <class 'decimal.Decimal'>

**Comment by chfw** [comment]
Your library are compatible with each other. The KeyError is not the cause though. The default renderer to console failed to handle Decimal type.

What about putting a break point here and change file_type to 'csv', then you could do print(file_content.getvalue()): 

https://github.com/pyexcel/pyexcel-webio/blob/master/pyexcel_webio/__init__.py#L261

I am trying to see if there are content obtained from your data table.

**Comment by maltebeckmann** [comment]
I tried the print(file_content.getvalue()) and it printed tons and tons of text. However, I do have a site with multiple-languages using django-parler.

So I tweaked the custom bit a little, like this:

    elif atype == "custom":
        query_sets = City.objects.language('en').all()
        column_names = ['id', 'title', 'country']
        return excel.make_response_from_query_sets(
            query_sets,
            column_names,
            'xls',
            file_name="custom"
        )

And that output exactly what I wanted into the xls file. So it seems that make_response_from_a_table and make_response_from_tables may not work with django-parler.

So I guess everything is sort of fine with django-excel. I presume it's not feasible to make those functions above work with special django setups providing multilingual features.

Thanks for getting back to me!

**Comment by chfw** [comment]
pyexcel-io uses [model._meta.concrete_fields](https://github.com/pyexcel/pyexcel-io/blob/master/pyexcel_io/database/django.py#L31) to find out all columns. I think django-parler has modified model's behavior so pyexcel-io could not inspect all its fields. I will look at parler further when I have time.

**Comment by maltebeckmann** [comment]
@chfw Cheers!
