### ISSUE TITLE
Data is not created in models and no error message shown

### ISSUE THREAD

**Issue by Pulkit-Sharma** [pyexcel/django-excel#34]
Hi I am trying to upload an excel file to update my model however the data is not updated neither any error message displayed.
```
@login_required
def productbulk(request):
    if request.method == "POST":
        form = productupload(request.POST, request.FILES)
        def choice_func(row):
            q = request.user
            row[0] = q
            return row
        if form.is_valid():
            request.FILES['select_excel_file'].save_book_to_database(
                models=[productmodel],
                initializers=[choice_func],
                mapdicts=[
                    
                    ['user','product_name','uom','description','HSN_code','price','discount_rate','sgst_rate','cgst_rate','igst_rate']]
            )
            return HttpResponseRedirect(reverse('productbulk'),messages.add_message(request, messages.SUCCESS,'Product added Succesfully'))   
    else:
        form = productupload()
    return render(request,'productbulk.html',{'form': form})
```

**Comment by chfw** [comment]
I would suggest that you put a break point and step through your code.

    @login_required
    def productbulk(request):
        import pdb;pdb.set_trace()
        if request.method == "POST":

**Comment by Pulkit-Sharma** [comment]
I think in documentation this point needs to be mentioned:

While importing data in excel default value provided in models are not considered. Problem in my case was that in model I had a field.
igst_rate = models.charfield(default=0)

It was not considering the blank cell in excel. I had to fill some value.
I solved it by modifying the field with null=true,blank=true.
