### ISSUE TITLE
Working fine on development but not on production

### ISSUE THREAD

**Issue by Pulkit-Sharma** [pyexcel/django-excel#35]
@chfw  Thanks a lot for this wonderful package. It made my day.
However the issue I am facing now is that it works perfectly fine on my local machine (OS-Seira) but when deployed on production server (Ubuntu), it does not work.

Do we need to have MS excel installed on server? As only difference I see is that on my local machine I have installed MS excel.

**Comment by chfw** [comment]
It has no dependency to MS excel and no dependency to OS platforms. Please share the trace or error message for further investigation.

**Comment by Pulkit-Sharma** [comment]
@chfw Tried your last suggested pdb.trace() but it hangs and does not do anything. Is it possible to get trackback from package itself.
I mean it returns valid httpresponse but nothing happens. Data is not saved to  db.

**Comment by chfw** [comment]
Here is logging instructions: http://pyexcel.readthedocs.io/en/latest/logging.html

**Comment by Pulkit-Sharma** [comment]
Nothing seems to work on development server, working perfectly on local machine. Any tutorial online explaining deployment in production server!!!

**Comment by chfw** [comment]
Please make your dev, test and production environment the same. Otherwise, you get this problem. Works in dev but not in production.

No traceback, no info,  I am afraid that I could not help further.

**Comment by chfw** [comment]
It hangs maybe because of the break point. You can do print instead to your function and you need to try bullet-tracing to find out where the code goes.

**Comment by Pulkit-Sharma** [comment]
@chfw anything to do with db. In local I have Sqlite and on server its postgres.

I have been trying from past couple of days but no solution.

Here is my code:
```
@login_required
def customerbulk(request):    
    action = 1
    if request.method == "POST":
        form = productupload(request.POST, request.FILES)
        def choice_func(row):
            q = request.user
            row[0] = q
            return row
        if form.is_valid():
            request.FILES['select_excel_file'].save_book_to_database(
                models=[customer],
                initializers=[choice_func],
                mapdicts=[
                    
                    ['user','name','address','state_code','shipping_address','shipping_state_code','email','telephone','GSTIN','PAN','discount','notes']]
            )
            return HttpResponseRedirect(reverse('customerbulk'),messages.add_message(request, messages.SUCCESS,'Customers added Succesfully'))       
    else:
        form = productupload()
    return render(request,'productbulk.html',{'form': form,'action':action,})
```
Have done everything as suggested in readthedocs.

**Comment by chfw** [comment]
Please place print statements here to trace the program flow:

https://github.com/pyexcel/pyexcel-io/blob/master/pyexcel_io/database/django.py#L52
https://github.com/pyexcel/pyexcel-io/blob/master/pyexcel_io/database/django.py#L64

And have you checked your django log yet? 
And have you read [this note yet](http://django-excel.readthedocs.io/en/latest/#what-to-do-if-import-data-overlaps-existing-data-in-the-database)?

**Comment by Pulkit-Sharma** [comment]
@chfw  With code above where do I place any tracing code? I am not from CS background and little difficult to understand the code links you provided!!!
Where do I write all these? Below my above code?

**Comment by chfw** [comment]
first, get a copy locally:

    git clone https://github.com/pyexcel/pyexcel-io.git

then, open pyexcel_io/database/django.py

         def write_row(self, array):
            if is_empty_array(array):
                print(constants.MESSAGE_EMPTY_ARRAY)
            else:
                new_array = swap_empty_string_for_none(array)
                print("----> 1")
                model_to_be_created = new_array
                if self.__initializer is not None:
                    print("----> 2")
                    model_to_be_created = self.__initializer(new_array)
                if model_to_be_created:
                    print("----> 3")
                    self.__objs.append(self.__model(**dict(
                        zip(self.__column_names, model_to_be_created)
                    )))

Third, apply the sam for the next function line.

Then, python setup.py install --> install a custom pyexcel-io, which will then do bullet-tracing for you.

**Comment by chfw** [comment]
Come back a bit. The data import function does its best when your database is empty. If you have data in your database and you do the same data import, when your data has the same data record as in the database, you will not be able to create it and django-excel will skip the data. 

Imagine a use case where you have a data file and you have imported it into an empty database. Now if you import the data file at the second time, your database will not be changed because your data has been imported. Database will not allow to create duplicated data.

**Comment by Pulkit-Sharma** [comment]
@chfw But my database is empty.

**Comment by chfw** [comment]
Wel, then try the tracing instruction to get to know more.

**Comment by chfw** [comment]
please try pyexcel-io v0.4.2 which will at latest stop importing if anything goes wrong.

**Comment by chfw** [comment]
No response. Reopen if it persists.
