### ISSUE TITLE
Depreciated usage. please use dest_file_name

### ISSUE THREAD

**Issue by furins** [pyexcel/django-excel#8]
I've an issue (I receive "Depreciated usage. please use dest_file_name" warning) that seems related to some comments in https://github.com/chfw/django-excel/issues/1. It should not be generated by code:

    import django_excel as excel
    import pyexcel.ext.xls
    from .models import MyModel
    
    qs = MyModel.objects.all()
    column_names = ['field1', 'field2']
    sheet = excel.pe.get_sheet(query_sets=qs, column_names=column_names)
    sheet.row[0] = ["field1", "field2"]
    sheet.name = 'test'
    response = excel.make_response(sheet, 'xls', 200)
    response['Content-Disposition'] = 'attachment;      
    filename="export_test_{:%d_%m_%Y}.xls"'.format(datetime.datetime.now())

and this is my `pip freeze` (the relevant parts of it, more precisely):

    Django==1.8.4
    django-excel==0.0.2
    future==0.15.2
    openpyxl==2.2.6
    pyexcel==0.1.7
    pyexcel-io==0.0.6
    pyexcel-webio==0.0.3
    pyexcel-xls==0.0.7
    pyexcel-xlsx==0.0.6
    pytz==2015.4
    six==1.9.0
    Unidecode==0.4.18
    virtualenv==13.0.3
    xlrd==0.9.4
    xlwt==1.0.0
    xlwt-future==0.8.0

not a big deal but I'd like to solve it before it becomes an error :)

**Comment by chfw** [comment]
try this newer pyexcel:

    pip install git+https://github.com/chfw/pyexcel.git

It should tell which one is actual deprecated.
